import { useState } from 'react'
import { useForm } from '@tanstack/react-form'
import { Input } from '@/components/ui/Input'
import { Button } from '@/components/ui/Button'
import { AttributesEditor, type Attribute } from './AttributesEditor'
import { ImageUploader, type ImageFile } from './ImageUploader'
import { StockHistoryPanel } from './StockHistoryPanel'
import {
  defaultProductValues,
  type ProductFormValues,
} from '@/lib/validations/product'
import { slugify, formatPrice } from '@/lib/utils'
import { Save, Trash2 } from 'lucide-react'
import type { ProductDetail } from '@/server/admin/products'
import type { StockMovement } from '@/server/admin/images'
import { cn } from '@/lib/utils'

interface Category {
  id: number
  name: string
  slug: string
}

interface Brand {
  id: number
  name: string
  slug: string
}

interface ProductFormProps {
  mode: 'create' | 'edit'
  initialData?: ProductDetail
  categories: Category[]
  brands: Brand[]
  stockMovements?: StockMovement[]
  onSubmit: (data: ProductFormValues) => Promise<void>
  onDelete?: () => Promise<void>
  onImageUpload?: (
    file: File,
    position: number,
    isMain: boolean
  ) => Promise<{ id: number; url: string }>
  onImageDelete?: (imageId: number) => Promise<void>
  isSubmitting: boolean
  isDeleting?: boolean
}

export function ProductForm({
  mode,
  initialData,
  categories,
  brands,
  stockMovements = [],
  onSubmit,
  onDelete,
  onImageUpload,
  onImageDelete,
  isSubmitting,
  isDeleting = false,
}: ProductFormProps) {
  // Initialize images from initialData
  const [images, setImages] = useState<ImageFile[]>(() => {
    if (initialData?.images) {
      return initialData.images.map((img) => ({
        id: img.id,
        url: img.url,
        position: img.position ?? 0,
        isMain: img.isMain ?? false,
        isNew: false,
      }))
    }
    return []
  })

  // Slug auto-generation tracking
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(mode === 'create')

  // Validation errors state
  const [errors, setErrors] = useState<Record<string, string>>({})

  const form = useForm({
    defaultValues: {
      ...(defaultProductValues as ProductFormValues),
      ...(initialData
        ? {
            name: initialData.name,
            slug: initialData.slug,
            description: initialData.description || '',
            sku: initialData.sku,
            ean: initialData.ean || '',
            brandId: initialData.brandId,
            categoryId: initialData.categoryId,
            priceHt: initialData.priceHt,
            taxRate: initialData.taxRate,
            stockQuantity: initialData.stockQuantity,
            stockAlertThreshold: initialData.stockAlertThreshold || 5,
            isActive: initialData.isActive ?? true,
            featured: initialData.featured ?? false,
            attributes:
              initialData.attributes?.map((a) => ({
                id: a.id,
                name: a.name,
                value: a.value,
              })) || [],
          }
        : {}),
    },
    onSubmit: async ({ value }) => {
      // Validate before submit
      const newErrors: Record<string, string> = {}

      if (!value.name || value.name.length < 2) {
        newErrors.name = 'Le nom doit contenir au moins 2 caractères'
      }
      if (!value.slug || value.slug.length < 2) {
        newErrors.slug = 'Le slug doit contenir au moins 2 caractères'
      } else if (!/^[a-z0-9-]+$/.test(value.slug)) {
        newErrors.slug =
          'Le slug ne peut contenir que des lettres minuscules, chiffres et tirets'
      }
      if (!value.sku) {
        newErrors.sku = 'Le SKU est requis'
      }
      if (value.priceHt < 0) {
        newErrors.priceHt = 'Le prix doit être positif'
      }

      setErrors(newErrors)

      if (Object.keys(newErrors).length > 0) {
        return
      }

      await onSubmit(value)
    },
  })

  const handleNameChange = (value: string) => {
    form.setFieldValue('name', value)
    if (slugAutoGenerated) {
      form.setFieldValue('slug', slugify(value))
    }
    if (errors.name) {
      setErrors((prev) => ({ ...prev, name: '' }))
    }
  }

  const handleSlugChange = (value: string) => {
    form.setFieldValue('slug', value)
    setSlugAutoGenerated(false)
    if (errors.slug) {
      setErrors((prev) => ({ ...prev, slug: '' }))
    }
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
        form.handleSubmit()
      }}
      className="space-y-8"
    >
      {/* Basic Info Section */}
      <div className="rounded-[--radius-lg] border border-[--border-default] bg-[--bg-card] p-5">
        <h2 className="mb-4 font-semibold text-[--text-primary]">
          Informations générales
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <form.Field name="name">
            {(field) => (
              <Input
                label="Nom du produit *"
                value={field.state.value}
                onChange={(e) => handleNameChange(e.target.value)}
                error={errors.name}
                placeholder="Ex: Ordinateur portable Dell XPS 15"
              />
            )}
          </form.Field>

          <form.Field name="slug">
            {(field) => (
              <Input
                label="Slug (URL) *"
                value={field.state.value}
                onChange={(e) => handleSlugChange(e.target.value)}
                error={errors.slug}
                placeholder="ordinateur-portable-dell-xps-15"
                hint="Généré automatiquement à partir du nom"
              />
            )}
          </form.Field>

          <form.Field name="sku">
            {(field) => (
              <Input
                label="SKU (Référence interne) *"
                value={field.state.value}
                onChange={(e) =>
                  field.handleChange(e.target.value.toUpperCase())
                }
                error={errors.sku}
                placeholder="DELL-XPS15-2024"
              />
            )}
          </form.Field>

          <form.Field name="ean">
            {(field) => (
              <Input
                label="Code EAN"
                value={field.state.value}
                onChange={(e) => field.handleChange(e.target.value)}
                placeholder="1234567890123"
              />
            )}
          </form.Field>

          <div className="md:col-span-2">
            <form.Field name="description">
              {(field) => (
                <div className="w-full">
                  <label className="mb-1.5 block text-sm font-medium text-[--text-primary]">
                    Description
                  </label>
                  <textarea
                    value={field.state.value}
                    onChange={(e) => field.handleChange(e.target.value)}
                    rows={4}
                    className={cn(
                      'w-full rounded-[--radius-md] border border-[--border-default] bg-[--bg-card] px-3.5 py-2.5',
                      'text-[15px] text-[--text-primary] placeholder:text-[--text-muted]',
                      'transition-all duration-[--duration-fast]',
                      'hover:border-[--border-strong]',
                      'focus:border-primary-400 focus:outline-none focus:ring-[3px] focus:ring-primary-500/10'
                    )}
                    placeholder="Description détaillée du produit..."
                  />
                </div>
              )}
            </form.Field>
          </div>
        </div>
      </div>

      {/* Category & Brand Section */}
      <div className="rounded-[--radius-lg] border border-[--border-default] bg-[--bg-card] p-5">
        <h2 className="mb-4 font-semibold text-[--text-primary]">
          Catégorie et marque
        </h2>

        <div className="grid gap-4 md:grid-cols-2">
          <form.Field name="categoryId">
            {(field) => (
              <div className="w-full">
                <label className="mb-1.5 block text-sm font-medium text-[--text-primary]">
                  Catégorie
                </label>
                <select
                  value={field.state.value ?? ''}
                  onChange={(e) =>
                    field.handleChange(
                      e.target.value ? Number(e.target.value) : null
                    )
                  }
                  className={cn(
                    'w-full rounded-[--radius-md] border border-[--border-default] bg-[--bg-card] px-3.5 py-2.5',
                    'text-[15px] text-[--text-primary]',
                    'transition-all duration-[--duration-fast]',
                    'hover:border-[--border-strong]',
                    'focus:border-primary-400 focus:outline-none focus:ring-[3px] focus:ring-primary-500/10'
                  )}
                >
                  <option value="">Sélectionner une catégorie</option>
                  {categories.map((cat) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))}
                </select>
              </div>
            )}
          </form.Field>

          <form.Field name="brandId">
            {(field) => (
              <div className="w-full">
                <label className="mb-1.5 block text-sm font-medium text-[--text-primary]">
                  Marque
                </label>
                <select
                  value={field.state.value ?? ''}
                  onChange={(e) =>
                    field.handleChange(
                      e.target.value ? Number(e.target.value) : null
                    )
                  }
                  className={cn(
                    'w-full rounded-[--radius-md] border border-[--border-default] bg-[--bg-card] px-3.5 py-2.5',
                    'text-[15px] text-[--text-primary]',
                    'transition-all duration-[--duration-fast]',
                    'hover:border-[--border-strong]',
                    'focus:border-primary-400 focus:outline-none focus:ring-[3px] focus:ring-primary-500/10'
                  )}
                >
                  <option value="">Sélectionner une marque</option>
                  {brands.map((brand) => (
                    <option key={brand.id} value={brand.id}>
                      {brand.name}
                    </option>
                  ))}
                </select>
              </div>
            )}
          </form.Field>
        </div>
      </div>

      {/* Pricing Section */}
      <div className="rounded-[--radius-lg] border border-[--border-default] bg-[--bg-card] p-5">
        <h2 className="mb-4 font-semibold text-[--text-primary]">
          Tarification
        </h2>

        <div className="grid gap-4 md:grid-cols-3">
          <form.Field name="priceHt">
            {(field) => (
              <Input
                label="Prix HT (€) *"
                type="number"
                step="0.01"
                min="0"
                value={field.state.value}
                onChange={(e) => field.handleChange(Number(e.target.value))}
                error={errors.priceHt}
                placeholder="0.00"
              />
            )}
          </form.Field>

          <form.Field name="taxRate">
            {(field) => (
              <Input
                label="Taux TVA (%)"
                type="number"
                step="0.1"
                min="0"
                max="100"
                value={field.state.value}
                onChange={(e) => field.handleChange(Number(e.target.value))}
              />
            )}
          </form.Field>

          <form.Subscribe selector={(state) => state.values}>
            {(values) => {
              const priceTtc = values.priceHt * (1 + values.taxRate / 100)
              return (
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-[--text-primary]">
                    Prix TTC (calculé)
                  </label>
                  <div className="flex h-11 items-center rounded-[--radius-md] border border-[--border-default] bg-surface-50 px-3.5 dark:bg-surface-800">
                    <span className="font-mono text-lg font-semibold text-primary-600">
                      {formatPrice(priceTtc)}
                    </span>
                  </div>
                </div>
              )
            }}
          </form.Subscribe>
        </div>
      </div>

      {/* Stock Section */}
      <div className="rounded-[--radius-lg] border border-[--border-default] bg-[--bg-card] p-5">
        <h2 className="mb-4 font-semibold text-[--text-primary]">Stock</h2>

        <div className="grid gap-4 md:grid-cols-2">
          <form.Field name="stockQuantity">
            {(field) => (
              <Input
                label="Quantité en stock"
                type="number"
                min="0"
                value={field.state.value}
                onChange={(e) => field.handleChange(Number(e.target.value))}
                disabled={mode === 'edit'}
                hint={
                  mode === 'edit'
                    ? "Utilisez l'ajustement de stock pour modifier"
                    : undefined
                }
              />
            )}
          </form.Field>

          <form.Field name="stockAlertThreshold">
            {(field) => (
              <Input
                label="Seuil d'alerte"
                type="number"
                min="0"
                value={field.state.value}
                onChange={(e) => field.handleChange(Number(e.target.value))}
                hint="Alerte quand le stock descend sous ce seuil"
              />
            )}
          </form.Field>
        </div>

        {/* Stock History for edit mode */}
        {mode === 'edit' && (
          <div className="mt-6 border-t border-[--border-default] pt-6">
            <StockHistoryPanel
              movements={stockMovements}
              currentStock={initialData?.stockQuantity || 0}
            />
          </div>
        )}
      </div>

      {/* Images Section */}
      <div className="rounded-[--radius-lg] border border-[--border-default] bg-[--bg-card] p-5">
        <ImageUploader
          images={images}
          onChange={setImages}
          onUpload={onImageUpload}
          onDelete={onImageDelete}
          disabled={mode === 'create'}
        />
        {mode === 'create' && (
          <p className="mt-2 text-sm text-[--text-muted]">
            Les images pourront être ajoutées après la création du produit.
          </p>
        )}
      </div>

      {/* Attributes Section */}
      <div className="rounded-[--radius-lg] border border-[--border-default] bg-[--bg-card] p-5">
        <form.Field name="attributes">
          {(field) => (
            <AttributesEditor
              attributes={field.state.value}
              onChange={(attrs) => field.handleChange(attrs as Attribute[])}
            />
          )}
        </form.Field>
      </div>

      {/* Status Section */}
      <div className="rounded-[--radius-lg] border border-[--border-default] bg-[--bg-card] p-5">
        <h2 className="mb-4 font-semibold text-[--text-primary]">Statut</h2>

        <div className="flex flex-wrap gap-6">
          <form.Field name="isActive">
            {(field) => (
              <label className="flex cursor-pointer items-center gap-3">
                <input
                  type="checkbox"
                  checked={field.state.value}
                  onChange={(e) => field.handleChange(e.target.checked)}
                  className="h-5 w-5 rounded border-[--border-default] text-primary-600 focus:ring-primary-500"
                />
                <span className="text-sm font-medium text-[--text-primary]">
                  Produit actif
                </span>
                <span className="text-sm text-[--text-muted]">
                  (visible dans le catalogue)
                </span>
              </label>
            )}
          </form.Field>

          <form.Field name="featured">
            {(field) => (
              <label className="flex cursor-pointer items-center gap-3">
                <input
                  type="checkbox"
                  checked={field.state.value}
                  onChange={(e) => field.handleChange(e.target.checked)}
                  className="h-5 w-5 rounded border-[--border-default] text-primary-600 focus:ring-primary-500"
                />
                <span className="text-sm font-medium text-[--text-primary]">
                  Produit vedette
                </span>
                <span className="text-sm text-[--text-muted]">
                  (affiché en page d'accueil)
                </span>
              </label>
            )}
          </form.Field>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-between">
        {mode === 'edit' && onDelete && (
          <Button
            type="button"
            variant="outline"
            onClick={() => {
              if (confirm('Voulez-vous vraiment désactiver ce produit ?')) {
                onDelete()
              }
            }}
            isLoading={isDeleting}
            className="text-error hover:bg-error-light hover:text-error-dark"
          >
            <Trash2 className="h-4 w-4" />
            Désactiver le produit
          </Button>
        )}

        <div className={cn('flex gap-3', mode === 'create' && 'ml-auto')}>
          <Button type="submit" variant="primary" isLoading={isSubmitting}>
            <Save className="h-4 w-4" />
            {mode === 'create' ? 'Créer le produit' : 'Enregistrer'}
          </Button>
        </div>
      </div>
    </form>
  )
}
