/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIndexRouteImport } from './routes/produits/index'
import { Route as CompteIndexRouteImport } from './routes/compte/index'
import { Route as CommanderIndexRouteImport } from './routes/commander/index'
import { Route as ProduitsSlugRouteImport } from './routes/produits/$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as AuthInscriptionRouteImport } from './routes/auth/inscription'
import { Route as AuthConnexionRouteImport } from './routes/auth/connexion'
import { Route as CompteCommandesIndexRouteImport } from './routes/compte/commandes/index'
import { Route as CompteCommandesOrderIdRouteImport } from './routes/compte/commandes/$orderId'
import { Route as CommanderConfirmationOrderIdRouteImport } from './routes/commander/confirmation.$orderId'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteIndexRoute = CompteIndexRouteImport.update({
  id: '/compte/',
  path: '/compte/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderIndexRoute = CommanderIndexRouteImport.update({
  id: '/commander/',
  path: '/commander/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInscriptionRoute = AuthInscriptionRouteImport.update({
  id: '/auth/inscription',
  path: '/auth/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnexionRoute = AuthConnexionRouteImport.update({
  id: '/auth/connexion',
  path: '/auth/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteCommandesIndexRoute = CompteCommandesIndexRouteImport.update({
  id: '/compte/commandes/',
  path: '/compte/commandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteCommandesOrderIdRoute = CompteCommandesOrderIdRouteImport.update({
  id: '/compte/commandes/$orderId',
  path: '/compte/commandes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderConfirmationOrderIdRoute =
  CommanderConfirmationOrderIdRouteImport.update({
    id: '/commander/confirmation/$orderId',
    path: '/commander/confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/panier': typeof PanierRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/commander': typeof CommanderIndexRoute
  '/compte': typeof CompteIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/commander/confirmation/$orderId': typeof CommanderConfirmationOrderIdRoute
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute
  '/compte/commandes': typeof CompteCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/panier': typeof PanierRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/commander': typeof CommanderIndexRoute
  '/compte': typeof CompteIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/commander/confirmation/$orderId': typeof CommanderConfirmationOrderIdRoute
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute
  '/compte/commandes': typeof CompteCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/panier': typeof PanierRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/commander/': typeof CommanderIndexRoute
  '/compte/': typeof CompteIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/commander/confirmation/$orderId': typeof CommanderConfirmationOrderIdRoute
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute
  '/compte/commandes/': typeof CompteCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/panier'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/commander'
    | '/compte'
    | '/produits'
    | '/commander/confirmation/$orderId'
    | '/compte/commandes/$orderId'
    | '/compte/commandes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/panier'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/commander'
    | '/compte'
    | '/produits'
    | '/commander/confirmation/$orderId'
    | '/compte/commandes/$orderId'
    | '/compte/commandes'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/panier'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/commander/'
    | '/compte/'
    | '/produits/'
    | '/commander/confirmation/$orderId'
    | '/compte/commandes/$orderId'
    | '/compte/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  PanierRoute: typeof PanierRoute
  AuthConnexionRoute: typeof AuthConnexionRoute
  AuthInscriptionRoute: typeof AuthInscriptionRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  CommanderIndexRoute: typeof CommanderIndexRoute
  CompteIndexRoute: typeof CompteIndexRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
  CommanderConfirmationOrderIdRoute: typeof CommanderConfirmationOrderIdRoute
  CompteCommandesOrderIdRoute: typeof CompteCommandesOrderIdRoute
  CompteCommandesIndexRoute: typeof CompteCommandesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/': {
      id: '/compte/'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander/': {
      id: '/commander/'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/inscription': {
      id: '/auth/inscription'
      path: '/auth/inscription'
      fullPath: '/auth/inscription'
      preLoaderRoute: typeof AuthInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connexion': {
      id: '/auth/connexion'
      path: '/auth/connexion'
      fullPath: '/auth/connexion'
      preLoaderRoute: typeof AuthConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/commandes/': {
      id: '/compte/commandes/'
      path: '/compte/commandes'
      fullPath: '/compte/commandes'
      preLoaderRoute: typeof CompteCommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/commandes/$orderId': {
      id: '/compte/commandes/$orderId'
      path: '/compte/commandes/$orderId'
      fullPath: '/compte/commandes/$orderId'
      preLoaderRoute: typeof CompteCommandesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander/confirmation/$orderId': {
      id: '/commander/confirmation/$orderId'
      path: '/commander/confirmation/$orderId'
      fullPath: '/commander/confirmation/$orderId'
      preLoaderRoute: typeof CommanderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  PanierRoute: PanierRoute,
  AuthConnexionRoute: AuthConnexionRoute,
  AuthInscriptionRoute: AuthInscriptionRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  CommanderIndexRoute: CommanderIndexRoute,
  CompteIndexRoute: CompteIndexRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
  CommanderConfirmationOrderIdRoute: CommanderConfirmationOrderIdRoute,
  CompteCommandesOrderIdRoute: CompteCommandesOrderIdRoute,
  CompteCommandesIndexRoute: CompteCommandesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
