/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIndexRouteImport } from './routes/produits/index'
import { Route as CompteIndexRouteImport } from './routes/compte/index'
import { Route as CommanderIndexRouteImport } from './routes/commander/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProduitsSlugRouteImport } from './routes/produits/$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as AuthInscriptionRouteImport } from './routes/auth/inscription'
import { Route as AuthConnexionRouteImport } from './routes/auth/connexion'
import { Route as CompteDevisIndexRouteImport } from './routes/compte/devis/index'
import { Route as CompteCommandesIndexRouteImport } from './routes/compte/commandes/index'
import { Route as AdminProduitsIndexRouteImport } from './routes/admin/produits/index'
import { Route as AdminDevisIndexRouteImport } from './routes/admin/devis/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as CompteDevisQuoteIdRouteImport } from './routes/compte/devis/$quoteId'
import { Route as CompteCommandesOrderIdRouteImport } from './routes/compte/commandes/$orderId'
import { Route as CommanderConfirmationOrderIdRouteImport } from './routes/commander/confirmation.$orderId'
import { Route as AdminDevisQuoteIdRouteImport } from './routes/admin/devis/$quoteId'
import { Route as AdminClientsEnAttenteRouteImport } from './routes/admin/clients/en-attente'
import { Route as AdminClientsUserIdRouteImport } from './routes/admin/clients/$userId'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteIndexRoute = CompteIndexRouteImport.update({
  id: '/compte/',
  path: '/compte/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderIndexRoute = CommanderIndexRouteImport.update({
  id: '/commander/',
  path: '/commander/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInscriptionRoute = AuthInscriptionRouteImport.update({
  id: '/auth/inscription',
  path: '/auth/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnexionRoute = AuthConnexionRouteImport.update({
  id: '/auth/connexion',
  path: '/auth/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteDevisIndexRoute = CompteDevisIndexRouteImport.update({
  id: '/compte/devis/',
  path: '/compte/devis/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteCommandesIndexRoute = CompteCommandesIndexRouteImport.update({
  id: '/compte/commandes/',
  path: '/compte/commandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProduitsIndexRoute = AdminProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevisIndexRoute = AdminDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const CompteDevisQuoteIdRoute = CompteDevisQuoteIdRouteImport.update({
  id: '/compte/devis/$quoteId',
  path: '/compte/devis/$quoteId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteCommandesOrderIdRoute = CompteCommandesOrderIdRouteImport.update({
  id: '/compte/commandes/$orderId',
  path: '/compte/commandes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderConfirmationOrderIdRoute =
  CommanderConfirmationOrderIdRouteImport.update({
    id: '/commander/confirmation/$orderId',
    path: '/commander/confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDevisQuoteIdRoute = AdminDevisQuoteIdRouteImport.update({
  id: '/devis/$quoteId',
  path: '/devis/$quoteId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsEnAttenteRoute = AdminClientsEnAttenteRouteImport.update({
  id: '/clients/en-attente',
  path: '/clients/en-attente',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsUserIdRoute = AdminClientsUserIdRouteImport.update({
  id: '/clients/$userId',
  path: '/clients/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/panier': typeof PanierRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/commander': typeof CommanderIndexRoute
  '/compte': typeof CompteIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/clients/en-attente': typeof AdminClientsEnAttenteRoute
  '/admin/devis/$quoteId': typeof AdminDevisQuoteIdRoute
  '/commander/confirmation/$orderId': typeof CommanderConfirmationOrderIdRoute
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute
  '/compte/devis/$quoteId': typeof CompteDevisQuoteIdRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/devis': typeof AdminDevisIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/compte/commandes': typeof CompteCommandesIndexRoute
  '/compte/devis': typeof CompteDevisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/panier': typeof PanierRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/commander': typeof CommanderIndexRoute
  '/compte': typeof CompteIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/clients/en-attente': typeof AdminClientsEnAttenteRoute
  '/admin/devis/$quoteId': typeof AdminDevisQuoteIdRoute
  '/commander/confirmation/$orderId': typeof CommanderConfirmationOrderIdRoute
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute
  '/compte/devis/$quoteId': typeof CompteDevisQuoteIdRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/devis': typeof AdminDevisIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/compte/commandes': typeof CompteCommandesIndexRoute
  '/compte/devis': typeof CompteDevisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/panier': typeof PanierRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/commander/': typeof CommanderIndexRoute
  '/compte/': typeof CompteIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/admin/clients/en-attente': typeof AdminClientsEnAttenteRoute
  '/admin/devis/$quoteId': typeof AdminDevisQuoteIdRoute
  '/commander/confirmation/$orderId': typeof CommanderConfirmationOrderIdRoute
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute
  '/compte/devis/$quoteId': typeof CompteDevisQuoteIdRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/devis/': typeof AdminDevisIndexRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
  '/compte/commandes/': typeof CompteCommandesIndexRoute
  '/compte/devis/': typeof CompteDevisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mcp'
    | '/panier'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/admin/'
    | '/commander'
    | '/compte'
    | '/produits'
    | '/admin/clients/$userId'
    | '/admin/clients/en-attente'
    | '/admin/devis/$quoteId'
    | '/commander/confirmation/$orderId'
    | '/compte/commandes/$orderId'
    | '/compte/devis/$quoteId'
    | '/admin/clients'
    | '/admin/devis'
    | '/admin/produits'
    | '/compte/commandes'
    | '/compte/devis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/panier'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/admin'
    | '/commander'
    | '/compte'
    | '/produits'
    | '/admin/clients/$userId'
    | '/admin/clients/en-attente'
    | '/admin/devis/$quoteId'
    | '/commander/confirmation/$orderId'
    | '/compte/commandes/$orderId'
    | '/compte/devis/$quoteId'
    | '/admin/clients'
    | '/admin/devis'
    | '/admin/produits'
    | '/compte/commandes'
    | '/compte/devis'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mcp'
    | '/panier'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/categories/$slug'
    | '/produits/$slug'
    | '/admin/'
    | '/commander/'
    | '/compte/'
    | '/produits/'
    | '/admin/clients/$userId'
    | '/admin/clients/en-attente'
    | '/admin/devis/$quoteId'
    | '/commander/confirmation/$orderId'
    | '/compte/commandes/$orderId'
    | '/compte/devis/$quoteId'
    | '/admin/clients/'
    | '/admin/devis/'
    | '/admin/produits/'
    | '/compte/commandes/'
    | '/compte/devis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  McpRoute: typeof McpRoute
  PanierRoute: typeof PanierRoute
  AuthConnexionRoute: typeof AuthConnexionRoute
  AuthInscriptionRoute: typeof AuthInscriptionRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  CommanderIndexRoute: typeof CommanderIndexRoute
  CompteIndexRoute: typeof CompteIndexRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
  CommanderConfirmationOrderIdRoute: typeof CommanderConfirmationOrderIdRoute
  CompteCommandesOrderIdRoute: typeof CompteCommandesOrderIdRoute
  CompteDevisQuoteIdRoute: typeof CompteDevisQuoteIdRoute
  CompteCommandesIndexRoute: typeof CompteCommandesIndexRoute
  CompteDevisIndexRoute: typeof CompteDevisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/': {
      id: '/compte/'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander/': {
      id: '/commander/'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/inscription': {
      id: '/auth/inscription'
      path: '/auth/inscription'
      fullPath: '/auth/inscription'
      preLoaderRoute: typeof AuthInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connexion': {
      id: '/auth/connexion'
      path: '/auth/connexion'
      fullPath: '/auth/connexion'
      preLoaderRoute: typeof AuthConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/devis/': {
      id: '/compte/devis/'
      path: '/compte/devis'
      fullPath: '/compte/devis'
      preLoaderRoute: typeof CompteDevisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/commandes/': {
      id: '/compte/commandes/'
      path: '/compte/commandes'
      fullPath: '/compte/commandes'
      preLoaderRoute: typeof CompteCommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produits/': {
      id: '/admin/produits/'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devis/': {
      id: '/admin/devis/'
      path: '/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AdminDevisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/compte/devis/$quoteId': {
      id: '/compte/devis/$quoteId'
      path: '/compte/devis/$quoteId'
      fullPath: '/compte/devis/$quoteId'
      preLoaderRoute: typeof CompteDevisQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/commandes/$orderId': {
      id: '/compte/commandes/$orderId'
      path: '/compte/commandes/$orderId'
      fullPath: '/compte/commandes/$orderId'
      preLoaderRoute: typeof CompteCommandesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander/confirmation/$orderId': {
      id: '/commander/confirmation/$orderId'
      path: '/commander/confirmation/$orderId'
      fullPath: '/commander/confirmation/$orderId'
      preLoaderRoute: typeof CommanderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/devis/$quoteId': {
      id: '/admin/devis/$quoteId'
      path: '/devis/$quoteId'
      fullPath: '/admin/devis/$quoteId'
      preLoaderRoute: typeof AdminDevisQuoteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/en-attente': {
      id: '/admin/clients/en-attente'
      path: '/clients/en-attente'
      fullPath: '/admin/clients/en-attente'
      preLoaderRoute: typeof AdminClientsEnAttenteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$userId': {
      id: '/admin/clients/$userId'
      path: '/clients/$userId'
      fullPath: '/admin/clients/$userId'
      preLoaderRoute: typeof AdminClientsUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsUserIdRoute: typeof AdminClientsUserIdRoute
  AdminClientsEnAttenteRoute: typeof AdminClientsEnAttenteRoute
  AdminDevisQuoteIdRoute: typeof AdminDevisQuoteIdRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminDevisIndexRoute: typeof AdminDevisIndexRoute
  AdminProduitsIndexRoute: typeof AdminProduitsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsUserIdRoute: AdminClientsUserIdRoute,
  AdminClientsEnAttenteRoute: AdminClientsEnAttenteRoute,
  AdminDevisQuoteIdRoute: AdminDevisQuoteIdRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminDevisIndexRoute: AdminDevisIndexRoute,
  AdminProduitsIndexRoute: AdminProduitsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  McpRoute: McpRoute,
  PanierRoute: PanierRoute,
  AuthConnexionRoute: AuthConnexionRoute,
  AuthInscriptionRoute: AuthInscriptionRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  CommanderIndexRoute: CommanderIndexRoute,
  CompteIndexRoute: CompteIndexRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
  CommanderConfirmationOrderIdRoute: CommanderConfirmationOrderIdRoute,
  CompteCommandesOrderIdRoute: CompteCommandesOrderIdRoute,
  CompteDevisQuoteIdRoute: CompteDevisQuoteIdRoute,
  CompteCommandesIndexRoute: CompteCommandesIndexRoute,
  CompteDevisIndexRoute: CompteDevisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
